"""Add holding model

Revision ID: d7c7f79524d9
Revises: 
Create Date: 2026-05-23 22:42:23.925797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'd7c7f79524d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'MUTUAL_FUND', 'ETF', 'BOND', 'GOLD', 'CRYPTO', 'INDEX', name='assetclass'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_halted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_metadata_ticker'), 'asset_metadata', ['ticker'], unique=True)
    op.create_table('economic_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('indicator_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name', 'indicator_date', name='uq_indicator_date')
    )
    op.create_index(op.f('ix_economic_indicators_indicator_name'), 'economic_indicators', ['indicator_name'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'price_date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=False)
    op.create_index('ix_market_prices_ticker_date', 'market_prices', ['ticker', 'price_date'], unique=False)
    op.create_table('market_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'signal_date', name='uq_signal_ticker_date')
    )
    op.create_index(op.f('ix_market_signals_ticker'), 'market_signals', ['ticker'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('tickers_mentioned', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('sectors_mentioned', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('sentiment', sa.Enum('BULLISH', 'BEARISH', 'NEUTRAL', name='sentimentlabel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_article_id', sa.UUID(), nullable=True),
    sa.Column('source_text_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_ticker'), 'sentiment_scores', ['ticker'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_ticker', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_buy_price', sa.Float(), nullable=False),
    sa.Column('buy_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tax_bracket', sa.String(length=50), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_expenses', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('emergency_savings', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('existing_investments', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('debt_obligations', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_investment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lump_sum_capability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('preferred_sectors', postgresql.ARRAY(Text()), nullable=False),
    sa.Column('ethical_investing', sa.Boolean(), nullable=False),
    sa.Column('domestic_vs_international', sa.Enum('DOMESTIC', 'INTERNATIONAL', 'BOTH', name='domesticinternational'), nullable=False),
    sa.Column('financial_goals', postgresql.ARRAY(Text()), nullable=False),
    sa.Column('risk_appetite', sa.Enum('CONSERVATIVE', 'MODERATELY_CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', 'VERY_AGGRESSIVE', name='riskappetite'), nullable=False),
    sa.Column('investment_horizon', sa.Enum('SHORT_TERM', 'MEDIUM_TERM', 'LONG_TERM', name='investmenthorizon'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'REBALANCED', name='portfoliostatus'), nullable=False),
    sa.Column('expected_cagr', sa.Float(), nullable=True),
    sa.Column('expected_volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('diversification_score', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('market_signals_used', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_assets_portfolio_id'), 'portfolio_assets', ['portfolio_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_portfolio_assets_portfolio_id'), table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('investor_profiles')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_sentiment_scores_ticker'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_signals_ticker'), table_name='market_signals')
    op.drop_table('market_signals')
    op.drop_index('ix_market_prices_ticker_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_economic_indicators_indicator_name'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_asset_metadata_ticker'), table_name='asset_metadata')
    op.drop_table('asset_metadata')
    # ### end Alembic commands ###
